Building room db jason
Sustainabli/sustainabli pull request #44
Opened 2024-02-08 20:55 UTC by JasonZ08

2024-02-11 06:38 UTC, michaelli00 requested changes
Can you add a video of updating a fume hood info?

2024-02-11 06:38 UTC, michaelli00 commented on src/components/ProfilePage/ProfilePage.js
> +                    {" "}
Why are there spaces here?

2024-02-11 06:38 UTC, michaelli00 commented on server/index.js
> +  const { sensor_id, fume_hood_name, building, room, organization_code } = req.body;
Update the reqBody comments above with the new fields

2024-02-13 17:06 UTC, michaelli00 requested changes

2024-02-13 17:06 UTC, michaelli00 commented on src/components/FumeHoodsPage/FumeHoodsPage.js
> +          updateSensor={props.updateSensors}
Extract the props on line 55 like this

{ availableSensors, updateSensors } = this.props;

2024-02-13 17:06 UTC, michaelli00 commented on src/components/FumeHoodsPage/components/FumeModalForm.js
>                    placeholder={selectedSensorInfo.fume_hood_name}
Updating the fields should edit on the existing fields (i.e. value={selectedSensorInfo.fume_hood_name}). Similar idea for the fields below building,  room, lab

2024-02-13 19:29 UTC, JasonZ08 commented on src/components/FumeHoodsPage/components/FumeModalForm.js
> +                <Form.Control type="input" placeholder="Lab"/>
I didn't add back-end / functionality to the Lab's field, so I decided to leave it as optional. That way testing whether or not buildings and rooms would work wouldn't require us to fill out the lab field.

2024-02-14 05:26 UTC, michaelli00 requested changes

2024-02-14 05:26 UTC, michaelli00 commented on src/components/FumeHoodsPage/components/FumeModalForm.js
> +                <Form.Control type="input" placeholder="Lab"/>
Actually, the lab refers to the group name I think from the db perspective. I used "group" to be organization agnostic (i.e. some organizations might use "lab" while others use "cohorts"). I think you can update the query on the server side.

2024-02-23 17:45 UTC, michaelli00 requested changes

2024-02-23 17:45 UTC, michaelli00 commented on server/Constants.js
> +  JOIN group_fume_hoods g
Make this an INNER JOIN and make the FROM, INNER JOIN, ON be on the same line (ref https://github.com/Sustainabli/sustainabli/blob/development/server/Constants.js#L158)

2024-02-23 17:45 UTC, michaelli00 commented on server/Constants.js
> +const DELETE_GROUP_ON_FUME_HOOD_UPDATE = `
We should make this a query to delete >=1 rows at a time

2024-02-23 17:45 UTC, michaelli00 commented on server/index.js
> +const { to } = require('mathjs');
Do we need this?

2024-02-23 17:45 UTC, michaelli00 commented on server/index.js
> +        await client.query(format(DELETE_GROUP_ON_FUME_HOOD_UPDATE, ele, sensor_id));
Rather than doing a delete query for each individual row, we can instead pass an array of elements we want to delete

so the query will look like

```
DELETE FROM group_fume_hoods
WHERE sensor_id=%L AND group_name IN %L
```

where the first param is sensor_id and the second param is a list of groups to remove

ref https://www.commandprompt.com/education/how-to-delete-multiple-rows-from-a-table-in-postgresql/

2024-02-23 17:45 UTC, michaelli00 commented on server/index.js
> +          await client.query(format(INSERT_GROUP_FUME_HOODS_QUERY, organization_code, ele, sensor_id, fume_hood_name));
We should insert all groups at the same time. See https://github.com/Sustainabli/sustainabli/blob/development/server/index.js#L175 for ref. 

Reason why we want to do this is to reduce the number of await calls to the server

2024-02-23 17:45 UTC, michaelli00 commented on src/components/FumeHoodsPage/FumeHoodsPage.js
> +                  return ele;
This is weird code. What are you going for here?

Pretty sure `{sensor.groups}` should work. Otherwise at the very least `{sensor.groups.map(ele => ele)}` should work

2024-02-23 17:45 UTC, michaelli00 commented on src/components/FumeHoodsPage/components/FumeModalForm.js
> +                  defaultValue={selectedSensorInfo.groups.map((ele) => {
What are you going for here? The groups split by a space? We can use join instead I think https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join

2024-02-23 17:45 UTC, michaelli00 commented on src/components/FumeHoodsPage/FumeHoodsPage.js
> +  // ex: [{fume_hood_name: 'testMac', organization_code: 'TTT', sensor_id: 'testMac'}, ...
nit: add the missing `]` at the end of this line

2024-02-23 21:51 UTC, JasonZ08 commented on src/components/FumeHoodsPage/FumeHoodsPage.js
> +                  return ele;
I just did this in case we want to format the elements in the group some sort of way

2024-02-24 22:11 UTC, michaelli00 commented on server/index.js
> +    var needsDelete = existing_groups.filter((ele) => !lab.includes(ele))
make this const

2024-02-24 22:11 UTC, michaelli00 commented on server/index.js
> +    var needsAdd = lab.filter((ele) => !existing_groups.includes(ele)).map((group) => [organization_code, group, sensor_id, fume_hood_name])
const

2024-02-24 22:11 UTC, michaelli00 commented on server/index.js
> +
clean up spacing between lines 516-525. Some empty lines not sure if needed

2024-02-24 23:36 UTC, merged